export { default as Login } from './Login';
export { default as Home } from './Home';
export { default as Checkout } from './Checkout';
export { default as Register } from './Register';
export { default as Admin } from './Admin';
export { default as Seller } from './Seller';
export { default as CustomerOrders } from './CustomerOrders';
export { default as CustomerDetails } from './CustomerDetails';
export { default as NotFound } from './NotFound';
